version: '3.8'
services:
  nestjs-app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOST: mongo
      DB_PORT: 27017
      JWT_SECRET: secretKey
      PORT: 4001


  mongo:
    container_name: mongodb
    image: mongo:6.0
    restart: always
    ports:
     - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
